name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build
      run: make build
    
    - name: Test version flag
      run: |
        ./bin/tree-sorter-ts --version
        ./bin/tree-sorter-ts --version | grep -E "tree-sorter-ts version (dev|[0-9]+\.[0-9]+\.[0-9]+)"
    
    - name: Test
      run: make test
    
    - name: Run benchmarks
      run: make bench