name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: darwin
            arch: amd64
            runner: macos-latest
            goos: darwin
            goarch: amd64
          - os: darwin
            arch: arm64
            runner: macos-latest
            goos: darwin
            goarch: arm64
          - os: linux
            arch: amd64
            runner: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: linux
            arch: arm64
            runner: ubuntu-latest
            goos: linux
            goarch: arm64
          - os: windows
            arch: amd64
            runner: windows-latest
            goos: windows
            goarch: amd64
          - os: windows
            arch: arm64
            runner: windows-latest
            goos: windows
            goarch: arm64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o tree-sorter-ts${{ matrix.os == 'windows' && '.exe' || '' }} ./cmd/tree-sorter-ts
      
      - name: Create archive
        run: |
          tar -czf tree-sorter-ts_${{ matrix.os }}_${{ matrix.arch }}.tar.gz tree-sorter-ts${{ matrix.os == 'windows' && '.exe' || '' }}
        if: matrix.os != 'windows'
      
      - name: Create archive (Windows)
        run: |
          tar -czf tree-sorter-ts_${{ matrix.os }}_${{ matrix.arch }}.tar.gz tree-sorter-ts.exe
        if: matrix.os == 'windows'
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tree-sorter-ts_${{ matrix.os }}_${{ matrix.arch }}
          path: tree-sorter-ts_${{ matrix.os }}_${{ matrix.arch }}.tar.gz

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: artifacts/**/tree-sorter-ts_*.tar.gz
          generate_release_notes: true

  publish-npm:
    name: Publish to NPM
    needs: release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Update package version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          npm version $VERSION --no-git-tag-version
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}